# Generated by Django 2.2.5 on 2019-09-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='addressNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
