# Generated by Django 2.2.5 on 2019-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0002_auto_20190917_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='person',
            name='cellPhone',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='cep',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='dateOfBirth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='rg',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
