# Generated by Django 2.2.5 on 2019-09-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0005_auto_20190921_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='rg',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
