# Generated by Django 2.2.5 on 2019-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0007_auto_20190921_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cellPhone',
            new_name='cellphone',
        ),
    ]
