# Generated by Django 2.2.5 on 2019-09-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0009_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='installments',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
