# Generated by Django 2.2.5 on 2019-09-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemcrud', '0011_auto_20190921_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestModel',
        ),
    ]
